site_name: Vector Tactics - Arma 3 Clan
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red
nav:
  - index.md
  - konfiguracja.md
  - podstawy.md
  - medic.md
  - struktura_dowodzenia.md
  - formacje.md
  - Role:
      - pl.md
      - sl.md
      - tl.md
      # - sniper.md
      - JTAC-heli.md
  - Radio:
      - radio.md
      - raporty.md
      - slownik_cas.md
      - 5liner.md
      - wezwanie_tbd.md
  - dodatkowe.md

